spring:
  profiles.active: test

---
spring:
  profiles: dev
  jpa:
    hibernate.ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/spring
    username: root
    password: password
server:
  port: 8090

---
spring:
  profiles: test
  jpa:
    hibernate.ddl-auto: create-drop
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
server:
  port: 8090
