spring:
  profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/ctof
    username: root
    password: password
  jpa:
    show-sql: true
  jackson.serialization.INDENT_OUTPUT: true
  redis:
    host: 192.168.99.100
server:
  port: 8090
  context-path: /api/v1

#logging.level.org.springframework.web: DEBUG

application:
  token:
    header: X-Auth-Token
    secret: ca$hc0w1!
    default-expiration: 15 # minutes

---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
  jpa:
    show-sql: true
  jackson.serialization.INDENT_OUTPUT: true
server:
  port: 8090
  context-path: /api/v1

application:
  token:
    header: X-Auth-Token
    secret: ca$hc0w1!
    default-expiration: 15 # minutes
