spring:
  profiles.active: dev

---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/ctof
    email: root
    password: password
  jpa:
    show-sql: true
  jackson.serialization.INDENT_OUTPUT: true
server:
  port: 8090
  context-path: /api/v1

#logging.level.org.springframework.web: DEBUG

app.token.header: X-Auth-Token
app.token.secret: ca$hc0w1!

---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
  jpa:
    show-sql: true
  jackson.serialization.INDENT_OUTPUT: true
server:
  port: 8090
  context-path: /api/v1

app.token.header: X-Auth-Token
app.token.secret: ca$hc0w1!
